### POST queryAvailableDrones
POST http://localhost:8080/api/v1/calcDeliveryPath
Content-Type: application/json

[
  {
    "id": 123,
    "date": "2025-12-22",
    "time": "14:30",
    "requirements": {
      "capacity": 0.75,
      "cooling": false,
      "heating": true,
      "maxCost": 13.5
    },

    "delivery": {
      "lng": -3.00,
      "lat": 55.121
    }
  }
]

### POST queryAvailableDrones
POST http://localhost:8080/api/v1/calcDeliveryPath
Content-Type: application/json

[
  {
    "id": 1,
    "date": "2025-01-01",
    "time": "14:30",
    "requirements": {
      "capacity": 0.01,
      "cooling": false,
      "heating": false,
      "maxCost": 1000.0
    },
    "delivery": {
      "lng": -3.189,
      "lat": 55.941
    }
  },
  {
    "id": 2,
    "date": "2025-01-02",
    "time": "14:30",
    "requirements": {
      "capacity": 0.01,
      "cooling": false,
      "heating": false,
      "maxCost": 1000.0
    },
    "delivery": {
      "lng": -3.180,
      "lat": 55.941
    }
  }
]

### POST queryAvailableDrones
POST http://localhost:8080/api/v1/calcDeliveryPath
Content-Type: application/json

[
  {
    "id": 1,
    "date": "2025-11-03",
    "time": "10:00:00",
    "requirements": {
      "capacity": 3,
      "maxCost": 6.0
    },
    "delivery": {
      "lng": -3.1883,
      "lat": 55.9444
    }
  }
]

### POST queryAvailableDrones
POST http://localhost:8080/api/v1/calcDeliveryPath
Content-Type: application/json

[
  {
    "id": 123,
    "date": "2025-12-22",
    "time": "14:30",
    "requirements": {
      "capacity": 0.75,
      "cooling": false,
      "heating": true,
      "maxCost": 13.5
    },

    "delivery": {
      "lng": -3.00,
      "lat": 55.121
    }
  }
]

### POST queryAvailableDrones
POST http://localhost:8080/api/v1/calcDeliveryPath
Content-Type: application/json

[
  {
    "id": 1,
    "date": "2025-01-01",
    "time": "14:30",
    "requirements": {
      "capacity": 0.01,
      "cooling": false,
      "heating": false,
      "maxCost": 1000.0
    },
    "delivery": {
      "lng": -3.189,
      "lat": 55.941
    }
  },
  {
    "id": 2,
    "date": "2025-01-02",
    "time": "14:30",
    "requirements": {
      "capacity": 0.01,
      "cooling": false,
      "heating": false,
      "maxCost": 1000.0
    },
    "delivery": {
      "lng": -3.180,
      "lat": 55.941
    }
  }
]

### POST queryAvailableDrones
POST http://localhost:8080/api/v1/calcDeliveryPath
Content-Type: application/json

[
  {
    "id": 1,
    "date": "2025-11-03",
    "time": "10:00:00",
    "requirements": {
      "capacity": 3,
      "maxCost": 6.0
    },
    "delivery": {
      "lng": -3.1883,
      "lat": 55.9444
    }
  }
]

### POST queryAvailableDrones
POST http://localhost:8080/api/v1/calcDeliveryPath
Content-Type: application/json

[
  {
    "id": 1,
    "date": "2025-01-02",
    "time": "12:00",
    "requirements": {
      "capacity": 4.0
    },
    "delivery": {
      "lng": -3.280,
      "lat": 55.941
    }
  },
  {
    "id": 2,
    "date": "2025-01-02",
    "time": "12:00",
    "requirements": {
      "capacity": 4.0
    },
    "delivery": {
      "lng": -3.180,
      "lat": 55.91
    }
  }
]

### POST Aisha_Test_1
POST http://localhost:8080/api/v1/calcDeliveryPath
Content-Type: application/json

[
  {
    "id": 123,
    "date": "2025-12-22",
    "time": "14:30",
    "requirements": {
      "capacity": 0.5,
      "maxCost": 50.0
    },
    "delivery": {
      "lng": -3.186,
      "lat": 55.945
    }
  },
  {
    "id": 124,
    "date": "2025-12-22",
    "time": "15:10",
    "requirements": {
      "capacity": 0.4,
      "maxCost": 50.0
    },
    "delivery": {
      "lng": -3.185,
      "lat": 55.946
    }
  }
]

### POST Aisha_Test_2
POST http://localhost:8080/api/v1/calcDeliveryPath
Content-Type: application/json

[
  {
    "id": 201,
    "date": "2025-12-01",
    "time": "08:00:00",
    "delivery": { "lng": -3.1865, "lat": 55.9447 },
    "requirements": {
      "capacity": 5.0,
      "cooling": false,
      "heating": false,
      "maxCost": null
    }
  },
  {
    "id": 202,
    "date": "2025-12-01",
    "time": "19:00:00",
    "delivery": { "lng": -3.1870, "lat": 55.9450 },
    "requirements": {
      "capacity": 5.0,
      "cooling": false,
      "heating": false,
      "maxCost": null
    }
  }
]

### POST Discord_test_1
POST http://localhost:8080/api/v1/calcDeliveryPath
Content-Type: application/json

[
  {
    "id": 1,
    "date": "2025-01-01",
    "time": "14:30",
    "requirements": {
      "capacity": 0.01,
      "cooling": false,
      "heating": false,
      "maxCost": 1000.0
    },
    "delivery": {
      "lng": -3.189,
      "lat": 55.941
    }
  },
  {
    "id": 2,
    "date": "2025-01-02",
    "time": "14:30",
    "requirements": {
      "capacity": 0.01,
      "cooling": false,
      "heating": false,
      "maxCost": 1000.0
    },
    "delivery": {
      "lng": -3.180,
      "lat": 55.941
    }
  }
]

### POST Discord_test_2
POST http://localhost:8080/api/v1/calcDeliveryPath
Content-Type: application/json

[
  {
    "id": 1,
    "date": "2025-12-22",
    "time": "14:30",
    "requirements": {
      "capacity": 0.75,
      "cooling": false,
      "heating": true,
      "maxCost": 13.5
    },

    "delivery": {
      "lng": -3.189,
      "lat": 55.941
    }
  },
  {
    "id": 2,
    "date": "2025-12-22",
    "time": "14:30",
    "requirements": {
      "capacity": 0.15,
      "cooling": false,
      "heating": false,
      "maxCost": 10.5
    },

    "delivery": {
      "lng": -3.189,
      "lat": 55.951
    }
  },
  {
    "id": 3,
    "date": "2025-12-22",
    "time": "14:30",
    "requirements": {
      "capacity": 0.85,
      "cooling": false,
      "heating": false,
      "maxCost": 8.0
    },

    "delivery": {
      "lng": -3.183,
      "lat": 55.95
    }
  },
  {
    "id": 4,
    "date": "2025-12-22",
    "time": "14:30",
    "requirements": {
      "capacity": 0.65,
      "cooling": false,
      "heating": true,
      "maxCost": 10.0
    },

    "delivery": {
      "lng": -3.172199382101411,
      "lat": 55.972584313088475
    }
  },
  {
    "id": 9,
    "date": "2025-12-22",
    "time": "14:30",
    "requirements": {
      "capacity": 0.15,
      "cooling": false,
      "heating": false,
      "maxCost": 10.5
    },

    "delivery": {
      "lng": -3.206735201926506,
      "lat": 55.955074502701166
    }
  },
  {
    "id": 23,
    "date": "2025-12-22",
    "time": "14:30",
    "requirements": {
      "capacity": 0.75,
      "cooling": false,
      "heating": true,
      "maxCost": 13.5
    },

    "delivery": {
      "lng": -3.1791924062780197,
      "lat": 55.97613963120534
    }
  }
]

### POST Discord_test_6
POST http://localhost:8080/api/v1/calcDeliveryPath
Content-Type: application/json

[
  {
    "id": 1,
    "date": "2025-12-22",
    "time": "14:30",
    "requirements": {
      "capacity": 0.75,
      "cooling": false,
      "heating": true,
      "maxCost": 13.5
    },

    "delivery": {
      "lng": -3.189,
      "lat": 55.941
    }
  },
  {
    "id": 2,
    "date": "2025-12-22",
    "time": "14:30",
    "requirements": {
      "capacity": 0.15,
      "cooling": false,
      "heating": false,
      "maxCost": 10.5
    },

    "delivery": {
      "lng": -3.189,
      "lat": 55.951
    }
  },
  {
    "id": 3,
    "date": "2025-12-22",
    "time": "14:30",
    "requirements": {
      "capacity": 6,
      "cooling": false,
      "heating": false,
      "maxCost": 5.0
    },

    "delivery": {
      "lng": -3.183,
      "lat": 55.95
    }
  },
  {
    "id": 4,
    "date": "2025-12-22",
    "time": "14:30",
    "requirements": {
      "capacity": 0.65,
      "cooling": false,
      "heating": true,
      "maxCost": 15.0
    },

    "delivery": {
      "lng": -3.213,
      "lat": 55.94
    }
  },
  {
    "id": 5,
    "date": "2025-12-22",
    "time": "14:30",
    "requirements": {
      "capacity": 0.75,
      "cooling": false,
      "heating": true,
      "maxCost": 13.5
    },

    "delivery": {
      "lng": -3.2088,
      "lat": 55.9799
    }
  },
  {
    "id": 6,
    "date": "2025-12-22",
    "time": "14:30",
    "requirements": {
      "capacity": 0.15,
      "cooling": false,
      "heating": false,
      "maxCost": 10.5
    },

    "delivery": {
      "lng": -3.1845,
      "lat": 55.9707
    }
  },
  {
    "id": 7,
    "date": "2025-12-22",
    "time": "14:30",
    "requirements": {
      "capacity": 0.65,
      "cooling": false,
      "heating": true,
      "maxCost": 15.0
    },

    "delivery": {
      "lng": -3.1795,
      "lat": 55.9434
    }
  },
  {
    "id": 8,
    "date": "2025-12-22",
    "time": "14:30",
    "requirements": {
      "capacity": 0.75,
      "cooling": false,
      "heating": true,
      "maxCost": 13.5
    },

    "delivery": {
      "lng": -3.1655,
      "lat": 55.9806
    }
  }
]

### POST Discord_test_8
POST http://localhost:8080/api/v1/calcDeliveryPath
Content-Type: application/json

[
  {
    "id": 1,
    "date": "2025-01-01",
    "time": "14:30",
    "requirements": {
      "capacity": 0.01,
      "cooling": false,
      "heating": false,
      "maxCost": 1000.0
    },
    "delivery": {
      "lng": -3.189,
      "lat": 55.941
    }
  },
  {
    "id": 2,
    "date": "2025-01-02",
    "time": "14:30",
    "requirements": {
      "capacity": 0.01,
      "cooling": false,
      "heating": false,
      "maxCost": 1000.0
    },
    "delivery": {
      "lng": -3.180,
      "lat": 55.941
    }
  }
]

### POST Discord_test_9
POST http://localhost:8080/api/v1/calcDeliveryPath
Content-Type: application/json

[
  {
    "id": 1,
    "date": "2025-01-01",
    "time": "14:30",
    "requirements": {
      "capacity": 4.0,
      "cooling": false,
      "heating": false,
      "maxCost": 4.5
    },

    "delivery": {
      "lng": -3.186,
      "lat": 55.944
    }
  },
  {
    "id": 2,
    "date": "2025-01-01",
    "time": "14:30",
    "requirements": {
      "capacity": 4.0,
      "cooling": false,
      "heating": false,
      "maxCost": 4.5
    },

    "delivery": {
      "lng": -3.184,
      "lat": 55.945
    }
  },
  {
    "id": 3,
    "date": "2025-01-01",
    "time": "14:30",
    "requirements": {
      "capacity": 4.0,
      "cooling": false,
      "heating": false,
      "maxCost": 4.5
    },

    "delivery": {
      "lng": -3.180,
      "lat": 55.980
    }
  },
  {
    "id": 4,
    "date": "2025-01-01",
    "time": "14:30",
    "requirements": {
      "capacity": 4.0,
      "cooling": false,
      "heating": true,
      "maxCost": 4.5
    },

    "delivery": {
      "lng": -3.175,
      "lat": 55.980
    }
  }
]